# Set index (default) Controller
index:
    path: /
    controller: App\Controller\IndexController::index

# Enable annotations in Controller files
controllers:
    resource: '../src/Controller/'
    type:     annotation
